#!/bin/sh
#
# GPG script to decrypt a file with our typical settings.
#
# Syntax:
# 
#     openssl-decrypt <file>
#     
# Example:
#
#     $ openssl-decrypt example.txt.aes > example.txt
# 
# 
# ## Related
# 
# These commands are related:
# 
#   * `gpg-encrypt`: use GPG to encrypt a file using our best settings.
#   
#   * `gpg-decrypt`: use GPG to decrypt a file using our best settings.
# 
#   * `openssl-encrypt`: use OpenSLL to encrypt a file using our best settings.
#   
#   * `openssl-decrypt`: use OpenSSL to decrypt a file using our best settings.
# 
# 
# ## Tracking
# 
#   * Command: openssl-decrypt
#   * Version: 1.0.0
#   * Created: 2017-09-14
#   * Updated: 2017-09-14
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)   
##
set -euf
umask_save=`umask`
umask 0077
openssl aes-256-cbc -d -salt -in "$1"
umask "$umask_save"
